import{a as f,S as L,i as c}from"./assets/vendor-D1eTGYtO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const v="https://pixabay.com/api/",w="45157582-00dbe423a45a27ad3340fe116";async function g(s,t){const r=new URLSearchParams({key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});try{return(await f.get(`${v}?${r}`)).data}catch(o){console.log(o)}}function m(s,t){const r=s.hits.map(e=>`<li
      class="gallery-item">
    <a class="gallery-link" href=${e.largeImageURL}>
    <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}"/>
    <div class="gallery-wrap">
    <p class="gallery-text"><span class="gallery-span">Likes</span>${e.likes}</p>
    <p class="gallery-text"><span class="gallery-span">Views</span>${e.views}</p>
    <p class="gallery-text"><span class="gallery-span">Comments</span>${e.comments}</p>
    <p class="gallery-text"><span class="gallery-span">Downloads</span>${e.downloads}</p>
    </div>
    </a>
    </li>`).join("");t.insertAdjacentHTML("beforeend",r),new L(".gallery-list a",{captionsData:"alt",captionDelay:250}).refresh()}const S=document.querySelector(".form-gallery"),y=document.querySelector(".form-gallery-input"),l=document.querySelector(".loader"),u=document.querySelector(".gallery-list"),n=document.querySelector(".btn");let i=1,b=15,p=0,h="";S.addEventListener("submit",x);n.addEventListener("click",C);async function x(s){s.preventDefault(),i=1,n.classList.add("visually-hidden"),u.innerHTML="",l.classList.remove("visually-hidden");let t=y.value.trim().toLowerCase();if(t===""){l.classList.add("visually-hidden");return}h=t;try{const r=await g(t,i);p=Math.ceil(r.totalHits/b),l.classList.add("visually-hidden"),r.hits.length===0?c.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}):(m(r,u),i<p&&n.classList.remove("visually-hidden"))}catch(r){l.classList.add("visually-hidden"),c.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:" Sorry, there was an error connecting to the server!"}),console.error(r)}finally{y.value="",s.target.reset()}}async function C(){i+=1,l.classList.remove("visually-hidden"),n.classList.add("visually-hidden");try{const s=await g(h,i);m(s,u);const r=document.querySelector(".gallery-list li").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"}),i>=p?c.error({position:"topRight",message:"We're sorry, there are no more posts to load"}):n.classList.remove("visually-hidden")}catch(s){c.error({position:"topRight",message:"Sorry, there was an error loading more images!"}),console.error(s)}finally{l.classList.add("visually-hidden")}}
//# sourceMappingURL=commonHelpers.js.map
