import{a as h,S as f,i as d}from"./assets/vendor-D1eTGYtO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const L="https://pixabay.com/api/",v="45157582-00dbe423a45a27ad3340fe116";async function g(a,t){const r=new URLSearchParams({key:v,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});try{return(await h.get(`${L}?${r}`)).data}catch(l){console.log(l)}}function m(a,t){const r=a.hits.map(e=>`<li
      class="gallery-item">
    <a class="gallery-link" href=${e.largeImageURL}>
    <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}"/>
    <div class="gallery-wrap">
    <p class="gallery-text"><span class="gallery-span">Likes</span>${e.likes}</p>
    <p class="gallery-text"><span class="gallery-span">Views</span>${e.views}</p>
    <p class="gallery-text"><span class="gallery-span">Comments</span>${e.comments}</p>
    <p class="gallery-text"><span class="gallery-span">Downloads</span>${e.downloads}</p>
    </div>
    </a>
    </li>`).join("");t.insertAdjacentHTML("beforeend",r),new f(".gallery-list a",{captionsData:"alt",captionDelay:250}).refresh()}const w=document.querySelector(".form-gallery"),u=document.querySelector(".form-gallery-input"),n=document.querySelector(".loader"),p=document.querySelector(".gallery-list"),i=document.querySelector(".btn");let o=1,S=15,y=0;w.addEventListener("submit",b);i.addEventListener("click",C);function b(a){a.preventDefault(),i.classList.add("visually-hidden"),p.innerHTML="",n.classList.remove("visually-hidden");let t=u.value.trim().toLowerCase();if(t===""){n.classList.add("visually-hidden");return}g(t,o).then(r=>{y=Math.ceil(r.totalHits/S),n.classList.add("visually-hidden"),r.hits.length===0?d.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}):(m(r,p),o<y&&i.classList.remove("visually-hidden"))}).catch(r=>{n.classList.add("visually-hidden"),d.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:" Sorry, there was an error connecting to the server!"}),console.error(r)}).finally(()=>{u.value="",a.target.reset()})}async function C(){o+=1;let a=u.value.trim().toLowerCase();const t=await g(a,o);m(t,p);const l=document.querySelector(".gallery-list li").getBoundingClientRect().height;if(window.scrollBy({top:l*2,behavior:"smooth"}),o>=y)return i.classList.add("visually-hidden"),d.error({position:"topRight",message:"We're sorry, there are no more posts to load"})}
//# sourceMappingURL=commonHelpers.js.map
